import type { ExhibitionDemo } from "../schema";
import { transcriptOf } from "./transcript";

/** A general-audience talk on the ethics of generative AI. */
export const AI_ETHICS_DEMO: ExhibitionDemo = {
  id: "demo-ai-ethics",
  label: "생성형 AI 윤리",
  audience: "생성형 AI를 써 본 일반 관중",
  teaser: "모두가 공감한 경험담 뒤에서, ‘책임은 모두에게’라는 결론이 왜 핵심 메시지를 흐렸는지 확인해 보세요.",
  commonInsight: {
    headline: "세 관중 모두 ‘존재하지 않는 논문’ 경험담에는 공감했지만, ‘책임은 모두에게 있다’는 결론에서 각자 누구의 책임인지 찾지 못했어요.",
    detail:
      "일반 시민은 자기 몫이 무엇인지, 서비스 기획자는 회사가 무엇을 해야 하는지, 윤리 연구자는 책임을 나누는 기준이 무엇인지를 기다렸어요. 핵심 메시지는 마지막 실천 제안에 와서야 다시 살아났어요.",
    sectionId: "map-rule",
    evidence: { segmentId: "seg-06", quote: "책임은 개발사, 사용자, 정부 모두에게 있다고 생각합니다" },
  },
  recommendation: {
    action: "‘모두의 책임’ 대신 오늘 이 자리의 청중이 지킬 책임 하나를 먼저 말하고, 규제 이야기는 그 근거로 붙이세요.",
    rewrite:
      "“개발사와 정부의 몫도 있지만, 오늘 여기서 우리가 바로 할 수 있는 건 하나예요. AI가 준 출처는 제출하기 전에 직접 열어 보는 겁니다.”",
    sectionId: "map-rule",
    difficultSectionId: "seg-06",
  },
  result: {
    presentationId: "demo-ai-ethics",
    title: "생성형 AI, 편리함 뒤에 남는 책임",
    durationSec: 236,
    analyzedAt: "2026-09-27T01:10:00.000Z",
    isSample: true,
    summary: {
      headline: "경험담으로 모두를 끌어들였지만, 규제와 책임을 다루는 구간에서 ‘누가 무엇을 해야 하는지’가 흐려져 핵심 메시지가 늦게 도착했어요.",
      intendedKeyMessage: "AI 결과에 이름을 거는 사람은 우리이므로, 출처 확인·사용 공개·개인정보 보호를 지키자.",
      priorityFixSectionId: "seg-06",
      strengths: [
        "존재하지 않는 논문을 인용받은 직접 경험으로 시작해 문제를 실감 나게 보여 줬어요.",
        "‘그 그림의 주인은 누구일까요?’처럼 청중이 스스로 생각해 보게 하는 질문을 던졌어요.",
        "마지막에 바로 따라 할 수 있는 실천 세 가지를 구체적으로 제시했어요.",
      ],
    },
    personas: [
      {
        id: "p-beginner",
        kind: "beginner",
        name: "생성형 AI를 써 본 일반 시민",
        description: "챗봇으로 글을 다듬어 본 적은 있지만 AI가 어떻게 만들어지는지는 모르는 관중이에요.",
        listensFor: "내 생활에서 무엇을 조심하면 되는지 쉽게 알려 주는지",
      },
      {
        id: "p-peer",
        kind: "peer",
        name: "AI 서비스를 기획하는 직장인",
        description: "회사에서 AI 기능을 기획하며 이용약관과 사용자 불만을 자주 접하는 관중이에요.",
        listensFor: "서비스를 만드는 입장에서 바로 적용할 기준이 있는지",
      },
      {
        id: "p-expert",
        kind: "expert",
        name: "AI 윤리 연구자",
        description: "AI 규제와 책임 분배를 연구하며 개념과 사례가 정확한지 보는 관중이에요.",
        listensFor: "원인 설명이 정확하고 책임을 나누는 기준이 분명한지",
      },
    ],
    personaFeedback: [
      {
        personaId: "p-beginner",
        understanding: "partly_lost",
        receivedKeyMessage: true,
        reaction: "없는 논문이 나왔다는 얘기에 깜짝 놀랐어요. 그런데 RLHF나 EU 법 얘기가 나올 때는 저랑 상관없는 얘기처럼 들렸어요. 마지막 세 가지는 바로 해 볼 수 있겠어요.",
        whatLanded: ["AI가 그럴듯하게 틀릴 수 있다는 경험담", "출처 확인·사용 공개·개인정보 보호 세 가지 실천"],
        whereLost: ["할루시네이션의 원인을 설명한 부분", "EU AI Act의 위험 기반 접근"],
        difficultSectionIds: ["seg-03", "seg-05"],
      },
      {
        personaId: "p-peer",
        understanding: "partly_lost",
        receivedKeyMessage: false,
        reaction: "규제 얘기까지는 흥미로웠는데 ‘책임은 모두에게 있다’에서 김이 빠졌어요. 서비스를 만드는 쪽이 무엇을 해야 하는지가 핵심일 줄 알았는데, 결론은 사용자 실천이더라고요.",
        whatLanded: ["저작권 문제를 그림 사례로 보여 준 부분", "투명성 의무라는 규제 방향"],
        whereLost: ["책임을 ‘모두에게’로 정리한 결론", "규제와 실천 제안의 연결"],
        difficultSectionIds: ["seg-06"],
      },
      {
        personaId: "p-expert",
        understanding: "followed",
        receivedKeyMessage: true,
        reaction: "흐름은 잘 따라갔어요. 다만 할루시네이션 원인을 편향과 한데 묶은 건 부정확하고, 책임 분배는 기준 없이 나열만 돼서 아쉬웠어요.",
        whatLanded: ["경험에서 규제, 실천으로 이어지는 구조", "사용 공개를 실천으로 제안한 점"],
        whereLost: ["할루시네이션 원인 설명의 정확성", "책임을 나누는 기준"],
        difficultSectionIds: ["seg-03", "seg-06"],
      },
    ],
    difficultSections: [
      {
        id: "seg-03",
        startSec: 44,
        endSec: 72,
        transcript: "이런 현상을 할루시네이션이라고 하는데, 학습 데이터의 편향과 RLHF 과정의 한계가 겹치면서 생깁니다.",
        highlight: "학습 데이터의 편향과 RLHF 과정의 한계가 겹치면서",
        category: "terminology",
        severity: "medium",
        reactions: [
          { personaId: "p-beginner", reaction: "할루시네이션까지는 들었는데 RLHF에서 완전히 멈췄어요." },
          { personaId: "p-peer", reaction: "RLHF는 들어 봤지만 편향과 어떻게 겹치는지 연결이 안 됐어요." },
          { personaId: "p-expert", reaction: "편향과 할루시네이션은 원인이 다른데 한데 묶였어요." },
        ],
        reason: "약어를 풀지 않았고, 서로 다른 두 원인을 한 문장에 묶어 처음 듣는 관중에게는 어렵고 전문가에게는 부정확하게 들려요.",
        cause: "TERM_CONFUSION",
        likelihood: "likely",
        pattern: "같은 문장인데 일반 시민은 용어 때문에, 윤리 연구자는 정확성 때문에 멈췄어요. 원인 설명을 쉬운 말 한 줄로 줄이면 두 문제가 함께 풀려요.",
        improvement: {
          suggestion: "약어 대신 동작으로 설명하고, 편향 이야기는 따로 떼어 말하세요.",
          rewrite: "“AI는 사실을 찾아보는 게 아니라, 가장 그럴듯한 다음 단어를 이어 붙여요. 그래서 없는 논문도 그럴듯하게 만들어 냅니다.”",
        },
      },
      {
        id: "seg-05",
        startSec: 100,
        endSec: 130,
        transcript: "EU AI Act는 위험 기반 접근으로 고위험 시스템에 투명성 의무를 부과하고 있고, 우리나라도 비슷한 논의가 진행 중입니다.",
        highlight: "위험 기반 접근으로 고위험 시스템에 투명성 의무를",
        category: "missing_context",
        severity: "medium",
        reactions: [
          { personaId: "p-beginner", reaction: "고위험 시스템이 뭔지, 그게 제 얘기인지 모르겠어요." },
          { personaId: "p-peer", reaction: "투명성 의무가 실제로 무엇을 공개하라는 건지 궁금했어요." },
        ],
        reason: "법 이름과 정책 용어를 예시 없이 제시해서, 관중이 자기 생활이나 일과 연결할 단서가 없어요.",
        cause: "CONTEXT_GAP",
        likelihood: "likely",
        pattern: "일반 시민은 자기와 상관없는 얘기로, 서비스 기획자는 무엇을 해야 하는지 모르는 얘기로 받아들였을 가능성이 높아요.",
        improvement: {
          suggestion: "‘고위험’의 예를 하나 들고, 투명성 의무가 사용자에게 어떻게 보이는지 말해 주세요.",
          rewrite: "“채용이나 대출 심사처럼 삶에 큰 영향을 주는 AI는, 사람이 아니라 AI가 판단했다는 걸 알려야 한다는 규칙이에요.”",
        },
      },
      {
        id: "seg-06",
        startSec: 130,
        endSec: 160,
        transcript: "결국 책임은 개발사, 사용자, 정부 모두에게 있다고 생각합니다.",
        highlight: "책임은 개발사, 사용자, 정부 모두에게 있다",
        category: "key_message",
        severity: "high",
        reactions: [
          { personaId: "p-peer", reaction: "모두에게 있다고 하니 결국 누구 책임인지 모르겠어요." },
          { personaId: "p-expert", reaction: "책임을 나누는 기준 없이 이름만 나열됐어요." },
          { personaId: "p-beginner", reaction: "저도 책임이 있다는 건데, 뭘 하라는 건지는 아직 몰랐어요." },
        ],
        reason: "발표의 결론이 될 문장이 누구에게나 해당하는 말로 끝나서, 뒤에 나오는 실천 제안이 핵심이라는 신호가 없어요.",
        cause: "PURPOSE_CONFUSION",
        likelihood: "high",
        pattern: "세 관중이 서로 다른 답을 기대했지만, 모두 ‘그래서 누가 무엇을?’이라는 같은 질문을 안고 이 구간을 지나갔어요.",
        improvement: {
          suggestion: "청중이 지킬 책임 하나를 먼저 말하고, 개발사와 정부의 몫은 그 뒤에 한 줄로 덧붙이세요.",
          rewrite:
            "“개발사와 정부의 몫도 있지만, 오늘 여기서 우리가 바로 할 수 있는 건 하나예요. AI가 준 출처는 제출하기 전에 직접 열어 보는 겁니다.”",
        },
      },
    ],
    missingExplanations: [
      {
        id: "me-hallucination",
        term: "할루시네이션",
        why: "일반 시민이 원인 설명에서 흐름을 놓쳤고, 연구자는 원인이 부정확하다고 느꼈어요.",
        suggestedExplanation: "AI가 사실이 아닌 내용을 사실처럼 그럴듯하게 만들어 내는 현상이에요.",
        personaIds: ["p-beginner", "p-expert"],
        sectionId: "seg-03",
      },
      {
        id: "me-rlhf",
        term: "RLHF",
        why: "약어를 풀지 않아 일반 시민과 기획자 모두 원인과 연결하지 못했어요.",
        suggestedExplanation: "사람이 AI의 답에 점수를 매겨, 사람이 좋아할 만한 답을 하도록 다듬는 학습 방법이에요.",
        personaIds: ["p-beginner", "p-peer"],
        sectionId: "seg-03",
      },
      {
        id: "me-risk-based",
        term: "위험 기반 접근",
        why: "일반 시민이 규제가 자기와 관련 있는지 판단하지 못했어요.",
        suggestedExplanation: "AI가 사람에게 줄 수 있는 피해가 클수록 더 엄격한 규칙을 적용하는 방식이에요.",
        personaIds: ["p-beginner"],
        sectionId: "seg-05",
      },
    ],
    exampleSuggestions: [
      {
        id: "ex-citation",
        concept: "출처를 직접 확인하는 습관",
        example: "“AI가 알려 준 논문 제목을 도서관 검색창에 그대로 넣어 보세요. 제 경우 세 편 중 한 편은 검색되지 않았어요.”",
        personaIds: ["p-beginner", "p-peer"],
        sectionId: "seg-07",
      },
      {
        id: "ex-disclosure",
        concept: "서비스에서의 투명성",
        example: "“답변 아래에 ‘AI가 작성한 초안입니다. 출처를 확인해 주세요’라는 한 줄을 붙이는 것만으로도 투명성 의무의 출발점이 돼요.”",
        personaIds: ["p-peer", "p-expert"],
        sectionId: "seg-05",
      },
    ],
    transcript: transcriptOf([
      { id: "seg-01", startSec: 0, endSec: 20, text: "과제를 하다가 생성형 AI에게 물어본 적 있으신가요? 저는 어제도 보고서 초안을 AI에게 맡겼습니다." },
      { id: "seg-02", startSec: 20, endSec: 44, text: "그런데 AI가 그럴듯하게 틀린 답을 내놓는 경우가 생각보다 많습니다. 제가 받은 답에는 존재하지 않는 논문이 인용돼 있었어요." },
      { id: "seg-03", startSec: 44, endSec: 72, text: "이런 현상을 할루시네이션이라고 하는데, 학습 데이터의 편향과 RLHF 과정의 한계가 겹치면서 생깁니다." },
      { id: "seg-04", startSec: 72, endSec: 100, text: "또 하나의 문제는 저작권입니다. AI가 만든 그림이 누군가의 화풍을 그대로 따라 한다면, 그 그림의 주인은 누구일까요?" },
      { id: "seg-05", startSec: 100, endSec: 130, text: "EU AI Act는 위험 기반 접근으로 고위험 시스템에 투명성 의무를 부과하고 있고, 우리나라도 비슷한 논의가 진행 중입니다." },
      { id: "seg-06", startSec: 130, endSec: 160, text: "결국 책임은 개발사, 사용자, 정부 모두에게 있다고 생각합니다." },
      {
        id: "seg-07",
        startSec: 160,
        endSec: 200,
        text: "그래서 저는 우리가 AI 답을 쓸 때 세 가지를 지키자고 제안합니다. 출처를 직접 확인하고, AI를 썼다고 밝히고, 개인정보는 넣지 않는 것입니다.",
      },
      { id: "seg-08", startSec: 200, endSec: 236, text: "AI는 편리한 도구지만, 그 결과에 이름을 거는 사람은 결국 우리입니다. 감사합니다." },
    ]),
    presentationMap: {
      sections: [
        {
          id: "map-hook",
          title: "경험으로 시작",
          startSec: 0,
          endSec: 44,
          summary: "존재하지 않는 논문을 인용받은 경험으로 문제를 꺼내요.",
          segmentIds: ["seg-01", "seg-02"],
          difficultSectionIds: [],
        },
        {
          id: "map-risk",
          title: "두 가지 위험",
          startSec: 44,
          endSec: 100,
          summary: "할루시네이션과 저작권 문제를 차례로 소개해요.",
          segmentIds: ["seg-03", "seg-04"],
          difficultSectionIds: ["seg-03"],
        },
        {
          id: "map-rule",
          title: "규제와 책임",
          startSec: 100,
          endSec: 160,
          summary: "해외 규제 흐름을 소개하고 책임이 누구에게 있는지 정리해요.",
          segmentIds: ["seg-05", "seg-06"],
          difficultSectionIds: ["seg-05", "seg-06"],
        },
        {
          id: "map-action",
          title: "실천 제안",
          startSec: 160,
          endSec: 236,
          summary: "AI를 쓸 때 지킬 세 가지를 제안하고 마무리해요.",
          segmentIds: ["seg-07", "seg-08"],
          difficultSectionIds: [],
        },
      ],
    },
    audienceHeatmap: {
      cells: [
        { sectionId: "map-hook", personaId: "p-beginner", reception: "clear", evidence: "없는 논문이 나왔다는 얘기에 바로 놀랐어요." },
        { sectionId: "map-hook", personaId: "p-peer", reception: "clear", evidence: "사용자 불만에서 자주 보는 사례라 공감됐어요." },
        { sectionId: "map-hook", personaId: "p-expert", reception: "clear", evidence: "구체적인 경험으로 문제를 연 점이 좋아요." },
        { sectionId: "map-risk", personaId: "p-beginner", reception: "lost", evidence: "할루시네이션까지는 들었는데 RLHF에서 완전히 멈췄어요." },
        { sectionId: "map-risk", personaId: "p-peer", reception: "partial", evidence: "RLHF는 들어 봤지만 편향과 어떻게 겹치는지 연결이 안 됐어요." },
        { sectionId: "map-risk", personaId: "p-expert", reception: "partial", evidence: "편향과 할루시네이션은 원인이 다른데 한데 묶였어요." },
        { sectionId: "map-rule", personaId: "p-beginner", reception: "partial", evidence: "고위험 시스템이 뭔지, 그게 제 얘기인지 모르겠어요." },
        { sectionId: "map-rule", personaId: "p-peer", reception: "lost", evidence: "모두에게 있다고 하니 결국 누구 책임인지 모르겠어요." },
        { sectionId: "map-rule", personaId: "p-expert", reception: "partial", evidence: "책임을 나누는 기준 없이 이름만 나열됐어요." },
        { sectionId: "map-action", personaId: "p-beginner", reception: "clear", evidence: "세 가지는 오늘부터 바로 해 볼 수 있겠어요." },
        { sectionId: "map-action", personaId: "p-peer", reception: "partial", evidence: "사용자 실천은 알겠는데 서비스를 만드는 쪽 얘기는 없었어요." },
        { sectionId: "map-action", personaId: "p-expert", reception: "clear", evidence: "사용 공개를 실천으로 제안한 점이 설득력 있어요." },
      ],
    },
    discovery: {
      headline: "세 관중 모두 ‘책임은 모두에게 있다’는 결론에서 각자 다른 답을 기다렸고, 그래서 핵심 메시지가 마지막 실천 제안에 와서야 도착했어요.",
      detail: "청중이 지킬 책임 하나를 결론 문장에 먼저 두면, 뒤의 실천 제안이 곧바로 핵심 메시지로 들려요.",
      sectionId: "map-rule",
      difficultSectionId: "seg-06",
      personaIds: ["p-beginner", "p-peer", "p-expert"],
    },
    keyMoments: [
      {
        id: "moment-1",
        kind: "interest_peak",
        startSec: 20,
        title: "관심이 가장 크게 올라간 구간",
        detail: "존재하지 않는 논문이 인용됐다는 경험담에서 세 관중 모두 문제를 실감했을 가능성이 높아요.",
        sectionId: "map-hook",
        personaIds: ["p-beginner", "p-peer", "p-expert"],
      },
      {
        id: "moment-2",
        kind: "first_drop",
        startSec: 44,
        title: "이해가 처음으로 떨어진 구간",
        detail: "RLHF라는 약어가 풀이 없이 나오면서 일반 시민의 이해가 처음 끊겼을 가능성이 높아요.",
        sectionId: "map-risk",
        difficultSectionId: "seg-03",
        personaIds: ["p-beginner", "p-peer"],
      },
      {
        id: "moment-3",
        kind: "common_question",
        startSec: 130,
        title: "여러 관중이 공통으로 질문을 가진 구간",
        detail: "‘책임은 모두에게 있다’는 말에 세 관중 모두 ‘그래서 누가 무엇을 해야 하지?’라고 물었을 가능성이 있어요.",
        sectionId: "map-rule",
        difficultSectionId: "seg-06",
        personaIds: ["p-beginner", "p-peer", "p-expert"],
      },
    ],
    naturalQuestions: [
      { id: "question-1", question: "AI가 없는 논문을 만들어 내는 건 정확히 왜 그런가요?", personaIds: ["p-beginner"], sectionId: "map-risk", startSec: 44 },
      { id: "question-2", question: "서비스를 만드는 회사는 구체적으로 무엇을 공개해야 하나요?", personaIds: ["p-peer"], sectionId: "map-rule", startSec: 100 },
      { id: "question-3", question: "개발사와 사용자의 책임은 어떤 기준으로 나눠야 하나요?", personaIds: ["p-expert", "p-peer"], sectionId: "map-rule", startSec: 130 },
    ],
  },
};
