import type { ExhibitionDemo } from "../schema";
import { transcriptOf } from "./transcript";

/** Explaining breadth-first search to people who have never heard of it. */
export const BFS_DEMO: ExhibitionDemo = {
  id: "demo-bfs",
  label: "BFS, 처음 듣는 사람에게",
  audience: "알고리즘을 처음 듣는 관중",
  teaser: "친구의 친구로 시작한 설명이 ‘큐’와 ‘O(V+E)’에서 어떻게 갈라지는지 확인해 보세요.",
  commonInsight: {
    headline: "세 관중 모두 ‘친구의 친구’ 비유에서는 함께 따라왔지만, 그 비유가 큐 동작 설명으로 이어지지 않아 절차 구간에서 각자 다른 이유로 멈췄어요.",
    detail:
      "처음 듣는 관중은 ‘큐’라는 단어에서, 다른 전공 대학생은 ‘꺼내고 넣는’ 순서에서, 현업 개발자는 설명 없이 던져진 O(V+E)에서 멈췄어요. 비유를 절차 설명까지 끌고 가면 세 관중이 같은 그림을 들고 다음 구간으로 넘어갈 수 있어요.",
    sectionId: "map-steps",
    evidence: { segmentId: "seg-05", quote: "큐에서 하나를 꺼낼 때마다 아직 방문하지 않은 이웃을 전부 큐에 넣습니다" },
  },
  recommendation: {
    action: "절차를 코드 용어로 바꾸기 전에, 앞에서 쓴 ‘친구 줄 세우기’ 비유로 한 바퀴를 먼저 보여 주세요.",
    rewrite:
      "“제 친구 세 명을 대기 줄에 세워요. 맨 앞 친구를 만나면, 그 친구의 친구 중 아직 안 만난 사람을 줄 맨 뒤에 세웁니다. 줄이 빌 때까지 이걸 반복하는 게 BFS예요. 이 대기 줄을 코드에서는 ‘큐’라고 불러요.”",
    sectionId: "map-steps",
    difficultSectionId: "seg-05",
  },
  result: {
    presentationId: "demo-bfs",
    title: "BFS, 가까운 친구부터 찾아가는 탐색",
    durationSec: 214,
    analyzedAt: "2026-09-27T01:00:00.000Z",
    isSample: true,
    summary: {
      headline: "‘친구의 친구’ 비유로 모두를 붙잡았지만, 큐와 복잡도가 나오는 절차 구간에서 세 관중 모두 한 번씩 흐름을 놓쳤어요.",
      intendedKeyMessage: "BFS는 가까운 곳부터 한 겹씩 넓혀 가기 때문에 가장 적은 단계로 도착하는 길을 찾아 준다.",
      priorityFixSectionId: "seg-05",
      strengths: [
        "‘친구의 친구’라는 질문으로 시작해 처음 듣는 관중도 문제를 바로 이해했어요.",
        "지하철 환승, 게임 미로처럼 일상 사례로 쓰임을 보여 줬어요.",
        "마지막 문장에서 핵심 메시지를 한 번 더 또렷하게 정리했어요.",
      ],
    },
    personas: [
      {
        id: "p-beginner",
        kind: "beginner",
        name: "코딩을 처음 배우는 고등학생",
        description: "프로그래밍 수업을 몇 번 들어 봤지만 그래프나 자료구조는 처음 듣는 관중이에요.",
        listensFor: "처음 듣는 용어를 쉬운 말과 그림으로 풀어 주는지",
      },
      {
        id: "p-peer",
        kind: "peer",
        name: "다른 전공 대학생",
        description: "엑셀과 간단한 파이썬은 써 봤고, 알고리즘 이름 정도만 들어 본 관중이에요.",
        listensFor: "절차가 순서대로 머릿속에 그려지는지",
      },
      {
        id: "p-expert",
        kind: "expert",
        name: "현업 개발자",
        description: "BFS를 실무 코드에서 써 본 개발자로, 설명이 정확하고 근거가 있는지 봐요.",
        listensFor: "용어와 복잡도 설명이 정확하고 왜 그런지까지 말하는지",
      },
    ],
    personaFeedback: [
      {
        personaId: "p-beginner",
        understanding: "partly_lost",
        receivedKeyMessage: true,
        reaction: "친구의 친구를 먼저 만난다는 건 확 와닿았어요. 그런데 ‘정점’, ‘간선’, ‘큐’가 한꺼번에 나오니까 그 뒤로는 비유만 붙잡고 들었어요.",
        whatLanded: ["가까운 친구부터 만난다는 비유", "지하철 환승 사례"],
        whereLost: ["정점·간선·큐를 한 문장에 몰아서 말한 부분", "큐에서 꺼내고 넣는 절차"],
        difficultSectionIds: ["seg-03", "seg-05"],
      },
      {
        personaId: "p-peer",
        understanding: "partly_lost",
        receivedKeyMessage: true,
        reaction: "개념은 알겠는데, 꺼내고 넣고를 말로만 들으니 지금 줄에 누가 서 있는지 머릿속에서 따라가기 어려웠어요.",
        whatLanded: ["너비 우선이라는 이름의 뜻", "최단 경로를 찾는다는 결론"],
        whereLost: ["큐 동작을 말로만 설명한 절차 구간"],
        difficultSectionIds: ["seg-05"],
      },
      {
        personaId: "p-expert",
        understanding: "followed",
        receivedKeyMessage: true,
        reaction: "설명 자체는 정확했어요. 다만 O(V+E)를 ‘그래서’로 바로 붙여서, 왜 그렇게 되는지 한 줄은 있었으면 좋겠어요.",
        whatLanded: ["visited 배열로 중복 방문을 막는다는 설명", "가중치 없는 최단 경로라는 결론"],
        whereLost: ["O(V+E)의 근거"],
        difficultSectionIds: ["seg-06"],
      },
    ],
    difficultSections: [
      {
        id: "seg-03",
        startSec: 40,
        endSec: 68,
        transcript: "그래프는 정점과 간선으로 이루어져 있고, BFS는 큐를 이용해 인접 정점을 방문 순서대로 처리합니다.",
        highlight: "정점과 간선으로 이루어져 있고, BFS는 큐를 이용해",
        category: "terminology",
        severity: "medium",
        reactions: [
          { personaId: "p-beginner", reaction: "정점, 간선, 큐가 한 문장에 다 나와서 무엇부터 이해해야 할지 몰랐어요." },
          { personaId: "p-peer", reaction: "큐는 들어 봤는데 여기서 왜 필요한지는 아직 몰랐어요." },
        ],
        reason: "처음 듣는 용어 세 개를 정의 없이 한 문장에 담았고, 바로 다음 문장에서야 비유가 나와 순서가 거꾸로 됐어요.",
        cause: "TERM_CONFUSION",
        likelihood: "likely",
        pattern: "현업 개발자에게는 익숙한 단어라 그냥 지나갔지만, 처음 듣는 관중은 용어 세 개를 동시에 받아 비유가 나오기 전에 이미 흐름을 놓쳤을 가능성이 높아요.",
        improvement: {
          suggestion: "비유를 먼저 말하고, 비유 속 사물에 용어 이름을 하나씩 붙여 주세요.",
          rewrite: "“사람 한 명을 점 하나, 친구 사이를 선 하나로 그려 볼게요. 이 점을 ‘정점’, 선을 ‘간선’이라고 불러요.”",
        },
      },
      {
        id: "seg-05",
        startSec: 95,
        endSec: 128,
        transcript:
          "방문한 정점은 visited 배열에 표시하고, 큐에서 하나를 꺼낼 때마다 아직 방문하지 않은 이웃을 전부 큐에 넣습니다. 이걸 큐가 빌 때까지 반복합니다.",
        highlight: "큐에서 하나를 꺼낼 때마다 아직 방문하지 않은 이웃을 전부 큐에 넣습니다",
        category: "abstract",
        severity: "high",
        reactions: [
          { personaId: "p-beginner", reaction: "꺼내고 넣는 게 무슨 뜻인지 그림이 안 그려졌어요." },
          { personaId: "p-peer", reaction: "지금 줄에 누가 서 있는지 말로만 따라가다 놓쳤어요." },
          { personaId: "p-expert", reaction: "정확하지만, 처음 듣는 사람에게는 한 바퀴 예시가 필요해 보여요." },
        ],
        reason: "BFS의 핵심 동작을 예시 없이 코드 용어로만 설명해서, 앞의 ‘친구’ 비유와 연결되지 않아요.",
        cause: "EXAMPLE_GAP",
        likelihood: "high",
        pattern: "배경지식이 다른 세 관중이 같은 문장에서 멈췄어요. 처음 듣는 관중은 ‘큐’를, 다른 전공 대학생은 순서를, 개발자는 청중 입장에서 예시의 부재를 짚었어요.",
        improvement: {
          suggestion: "앞에서 쓴 ‘친구 줄 세우기’ 비유로 한 바퀴를 직접 보여 준 뒤 코드 용어로 바꿔 말하세요.",
          rewrite:
            "“제 친구 세 명을 대기 줄에 세워요. 맨 앞 친구를 만나면, 그 친구의 친구 중 아직 안 만난 사람을 줄 맨 뒤에 세웁니다. 줄이 빌 때까지 이걸 반복하는 게 BFS예요.”",
        },
      },
      {
        id: "seg-06",
        startSec: 128,
        endSec: 150,
        transcript: "그래서 시간 복잡도는 O(V+E)가 됩니다.",
        highlight: "O(V+E)",
        category: "missing_context",
        severity: "low",
        reactions: [
          { personaId: "p-expert", reaction: "맞는 말이지만 ‘그래서’ 앞에 근거가 없어요." },
          { personaId: "p-beginner", reaction: "기호가 나와서 그냥 넘겼어요." },
        ],
        reason: "복잡도 표기를 근거 없이 결론처럼 붙였고, 처음 듣는 관중에게는 기호의 뜻도 전달되지 않아요.",
        cause: "LOGIC_GAP",
        likelihood: "possible",
        pattern: "개발자는 근거가 빠진 점을, 처음 듣는 관중은 기호 자체를 문제로 느꼈을 가능성이 있어요. 이 구간은 관중에 따라 빼거나 한 줄로 풀어 주면 돼요.",
        improvement: {
          suggestion: "복잡도를 말하려면 ‘모든 사람과 모든 친구 관계를 한 번씩만 본다’는 근거를 먼저 말하세요.",
          rewrite: "“모든 사람을 한 번씩, 모든 친구 관계를 한 번씩만 확인하니까, 사람 수와 관계 수를 더한 만큼만 일하면 돼요.”",
        },
      },
    ],
    missingExplanations: [
      {
        id: "me-queue",
        term: "큐",
        why: "처음 듣는 관중과 다른 전공 대학생이 절차 설명을 따라가지 못한 출발점이에요.",
        suggestedExplanation: "먼저 들어온 것이 먼저 나가는 대기 줄이에요. 매표소 줄처럼 앞에서 빠지고 뒤로 들어와요.",
        personaIds: ["p-beginner", "p-peer"],
        sectionId: "seg-05",
      },
      {
        id: "me-vertex-edge",
        term: "정점과 간선",
        why: "처음 듣는 관중이 용어 세 개를 한 번에 받으며 흐름을 놓쳤어요.",
        suggestedExplanation: "그래프를 그릴 때 점 하나가 정점, 점과 점을 잇는 선 하나가 간선이에요.",
        personaIds: ["p-beginner"],
        sectionId: "seg-03",
      },
      {
        id: "me-complexity",
        term: "O(V+E)",
        why: "현업 개발자는 근거를, 처음 듣는 관중은 기호의 뜻을 찾지 못했어요.",
        suggestedExplanation: "정점 수(V)와 간선 수(E)를 더한 만큼 일한다는 뜻이에요. 각각 한 번씩만 보기 때문이에요.",
        personaIds: ["p-expert", "p-beginner"],
        sectionId: "seg-06",
      },
    ],
    exampleSuggestions: [
      {
        id: "ex-line",
        concept: "큐로 한 겹씩 넓혀 가는 과정",
        example: "“나 → 친구 A, B, C가 줄을 서요. A를 만나면 A의 친구 D, E가 줄 뒤에 서요. 그래서 D, E는 B, C 다음에 만나게 됩니다.”",
        personaIds: ["p-beginner", "p-peer"],
        sectionId: "seg-05",
      },
      {
        id: "ex-subway",
        concept: "최단 경로가 보장되는 이유",
        example: "“환승 한 번으로 갈 수 있는 역을 전부 확인한 뒤에야 두 번 환승하는 역을 보니까, 처음 도착한 길이 곧 가장 적게 갈아타는 길이에요.”",
        personaIds: ["p-peer", "p-expert"],
        sectionId: "seg-07",
      },
    ],
    transcript: transcriptOf([
      { id: "seg-01", startSec: 0, endSec: 18, text: "여러분, 친구의 친구의 친구를 따라가면 몇 단계 만에 모르는 사람과 연결될까요? 오늘은 이 질문을 푸는 방법, BFS를 소개하려고 합니다." },
      { id: "seg-02", startSec: 18, endSec: 40, text: "BFS는 너비 우선 탐색이라는 뜻이에요. 출발점에서 가까운 곳부터 차례로 둘러보는 방법입니다." },
      { id: "seg-03", startSec: 40, endSec: 68, text: "그래프는 정점과 간선으로 이루어져 있고, BFS는 큐를 이용해 인접 정점을 방문 순서대로 처리합니다." },
      { id: "seg-04", startSec: 68, endSec: 95, text: "쉽게 말해 제 친구 세 명을 먼저 만나고, 그다음에 그 친구들의 친구를 만나는 식이에요." },
      {
        id: "seg-05",
        startSec: 95,
        endSec: 128,
        text: "방문한 정점은 visited 배열에 표시하고, 큐에서 하나를 꺼낼 때마다 아직 방문하지 않은 이웃을 전부 큐에 넣습니다. 이걸 큐가 빌 때까지 반복합니다.",
      },
      { id: "seg-06", startSec: 128, endSec: 150, text: "그래서 시간 복잡도는 O(V+E)가 됩니다." },
      { id: "seg-07", startSec: 150, endSec: 182, text: "지하철 앱이 환승이 가장 적은 길을 찾을 때도, 게임 캐릭터가 미로에서 최단 경로를 찾을 때도 이 방식이 쓰입니다." },
      { id: "seg-08", startSec: 182, endSec: 214, text: "정리하면, BFS는 가까운 곳부터 한 겹씩 넓혀 가기 때문에 가장 적은 단계로 도착하는 길을 찾아 줍니다. 감사합니다." },
    ]),
    presentationMap: {
      sections: [
        {
          id: "map-hook",
          title: "질문으로 시작",
          startSec: 0,
          endSec: 40,
          summary: "‘친구의 친구’ 질문으로 BFS가 푸는 문제를 소개해요.",
          segmentIds: ["seg-01", "seg-02"],
          difficultSectionIds: [],
        },
        {
          id: "map-concept",
          title: "그래프와 큐",
          startSec: 40,
          endSec: 95,
          summary: "그래프 용어를 소개하고 친구 비유로 풀어요.",
          segmentIds: ["seg-03", "seg-04"],
          difficultSectionIds: ["seg-03"],
        },
        {
          id: "map-steps",
          title: "탐색 절차",
          startSec: 95,
          endSec: 150,
          summary: "큐에서 꺼내고 이웃을 넣는 반복 절차와 복잡도를 설명해요.",
          segmentIds: ["seg-05", "seg-06"],
          difficultSectionIds: ["seg-05", "seg-06"],
        },
        {
          id: "map-use",
          title: "쓰임과 정리",
          startSec: 150,
          endSec: 214,
          summary: "지하철·게임 사례로 쓰임을 보여 주고 핵심을 정리해요.",
          segmentIds: ["seg-07", "seg-08"],
          difficultSectionIds: [],
        },
      ],
    },
    audienceHeatmap: {
      cells: [
        { sectionId: "map-hook", personaId: "p-beginner", reception: "clear", evidence: "친구의 친구 질문이라 바로 궁금해졌어요." },
        { sectionId: "map-hook", personaId: "p-peer", reception: "clear", evidence: "‘너비 우선’이라는 이름의 뜻이 바로 잡혔어요." },
        { sectionId: "map-hook", personaId: "p-expert", reception: "clear", evidence: "도입 질문이 BFS의 성질과 정확히 맞아요." },
        { sectionId: "map-concept", personaId: "p-beginner", reception: "partial", evidence: "정점, 간선, 큐가 한꺼번에 나와서 비유만 붙잡았어요." },
        { sectionId: "map-concept", personaId: "p-peer", reception: "clear", evidence: "친구 세 명 비유 덕분에 다시 따라왔어요." },
        { sectionId: "map-concept", personaId: "p-expert", reception: "clear", evidence: "용어 정의는 정확했어요." },
        { sectionId: "map-steps", personaId: "p-beginner", reception: "lost", evidence: "꺼내고 넣는 게 무슨 뜻인지 그림이 안 그려졌어요." },
        { sectionId: "map-steps", personaId: "p-peer", reception: "partial", evidence: "지금 줄에 누가 서 있는지 말로만 따라가다 놓쳤어요." },
        { sectionId: "map-steps", personaId: "p-expert", reception: "partial", evidence: "O(V+E)를 근거 없이 ‘그래서’로 붙였어요." },
        { sectionId: "map-use", personaId: "p-beginner", reception: "clear", evidence: "지하철 환승 얘기에서 다시 이해가 됐어요." },
        { sectionId: "map-use", personaId: "p-peer", reception: "clear", evidence: "게임 미로 사례로 쓰임이 확실해졌어요." },
        { sectionId: "map-use", personaId: "p-expert", reception: "clear", evidence: "가중치 없는 최단 경로라는 결론이 정확해요." },
      ],
    },
    discovery: {
      headline: "‘친구의 친구’ 비유는 모두에게 통했지만, 비유가 절차 설명까지 이어지지 않아 세 관중이 같은 문장에서 각자 다른 이유로 멈췄어요.",
      detail: "절차를 코드 용어로 바꾸기 전에 비유로 한 바퀴를 먼저 보여 주면, 세 관중이 같은 그림을 들고 다음 구간으로 넘어갈 수 있어요.",
      sectionId: "map-steps",
      difficultSectionId: "seg-05",
      personaIds: ["p-beginner", "p-peer", "p-expert"],
    },
    keyMoments: [
      {
        id: "moment-1",
        kind: "interest_peak",
        startSec: 0,
        title: "관심이 가장 크게 올라간 구간",
        detail: "‘친구의 친구의 친구’ 질문에서 세 관중 모두 답이 궁금해졌을 가능성이 높아요.",
        sectionId: "map-hook",
        personaIds: ["p-beginner", "p-peer", "p-expert"],
      },
      {
        id: "moment-2",
        kind: "first_drop",
        startSec: 40,
        title: "이해가 처음으로 떨어진 구간",
        detail: "정점·간선·큐가 정의 없이 한 문장에 나오면서 처음 듣는 관중의 이해가 흔들렸을 가능성이 높아요.",
        sectionId: "map-concept",
        difficultSectionId: "seg-03",
        personaIds: ["p-beginner"],
      },
      {
        id: "moment-3",
        kind: "common_question",
        startSec: 95,
        title: "여러 관중이 공통으로 질문을 가진 구간",
        detail: "큐 절차를 말로만 들으면서 ‘지금 누가 줄에 서 있지?’라는 질문이 세 관중 모두에게 생겼을 가능성이 있어요.",
        sectionId: "map-steps",
        difficultSectionId: "seg-05",
        personaIds: ["p-beginner", "p-peer", "p-expert"],
      },
    ],
    naturalQuestions: [
      { id: "question-1", question: "큐에서 꺼낸다는 건 줄 맨 앞 사람을 만난다는 뜻인가요?", personaIds: ["p-beginner", "p-peer"], sectionId: "map-steps", startSec: 95 },
      { id: "question-2", question: "왜 BFS로 찾은 길이 항상 가장 짧은 길이 되나요?", personaIds: ["p-peer"], sectionId: "map-use", startSec: 150 },
      { id: "question-3", question: "O(V+E)에서 V와 E를 더하는 이유는 무엇인가요?", personaIds: ["p-expert", "p-beginner"], sectionId: "map-steps", startSec: 128 },
    ],
  },
};
