import type { ExhibitionDemo } from "../schema";
import { transcriptOf } from "./transcript";

/** A student team presenting their school recycling project to the school. */
export const RECYCLING_DEMO: ExhibitionDemo = {
  id: "demo-recycling",
  label: "학교 분리배출 프로젝트",
  audience: "학생·선생님·교장 선생님이 함께 듣는 발표",
  teaser: "같은 해결 방안을 후배는 바로 받아들였는데, 결정해야 할 교장 선생님은 왜 멈췄는지 확인해 보세요.",
  commonInsight: {
    headline: "세 관중 모두 ‘한 달 동안 매일 수거함을 열어 봤다’는 직접 조사를 믿었지만, 시범 운영 결과를 ‘눈에 띄게’로만 말해 해결 방안을 받아들일 근거는 각자 찾지 못했어요.",
    detail:
      "신입생은 안내판이 효과 있었다는 말만으로 충분했지만, 환경 선생님은 얼마나 줄었는지를, 교장 선생님은 그 효과가 80만 원을 쓸 만한지를 기다렸어요. 조사 구간에서 보여 준 숫자의 힘을 해결 구간에서도 쓰면 세 관중이 같은 결론에 도착해요.",
    sectionId: "map-plan",
    evidence: { segmentId: "seg-07", quote: "오염률이 눈에 띄게 줄었습니다" },
  },
  recommendation: {
    action: "시범 운영 결과를 전후 숫자로 말하고, 그 숫자를 요청하는 결정(헹굼대 설치 80만 원)과 한 문장으로 이어 주세요.",
    rewrite:
      "“그림 안내판만 붙인 3학년 2반은 2주 만에 오염률이 47%에서 ○○%로 줄었습니다. 헹굼대까지 있으면 더 줄일 수 있어서, 80만 원으로 급식실 옆 헹굼대 설치를 제안드립니다.”",
    sectionId: "map-plan",
    difficultSectionId: "seg-07",
  },
  result: {
    presentationId: "demo-recycling",
    title: "우리 학교 분리배출, 왜 다시 섞일까",
    durationSec: 228,
    analyzedAt: "2026-09-27T01:20:00.000Z",
    isSample: true,
    summary: {
      headline: "직접 조사한 숫자로 문제는 모두에게 전달됐지만, 해결 방안에서는 효과와 요청이 흐려져 결정해야 할 교장 선생님이 가장 크게 흐름을 놓쳤어요.",
      intendedKeyMessage: "그림 안내판과 헹굼대로 헹궈서 버리는 습관을 도우면 학교 분리배출 오염률을 줄일 수 있으니, 헹굼대 설치를 승인해 달라.",
      priorityFixSectionId: "seg-07",
      strengths: [
        "한 달 동안 매일 수거함을 열어 본 직접 조사로 발표의 신뢰를 쌓았어요.",
        "오염률 47%, 설문 응답 62%처럼 문제의 크기를 숫자로 보여 줬어요.",
        "실제 한 반에서 먼저 시범 운영해 본 경험을 담았어요.",
      ],
    },
    personas: [
      {
        id: "p-beginner",
        kind: "beginner",
        name: "1학년 신입생",
        description: "분리배출은 매일 하지만 재질 구분이나 재활용 과정은 잘 모르는 관중이에요.",
        listensFor: "내가 내일부터 무엇을 다르게 하면 되는지",
      },
      {
        id: "p-expert",
        kind: "expert",
        name: "환경 교과 선생님",
        description: "재활용 선별 과정과 조사 방법을 수업에서 다루는 관중이에요.",
        listensFor: "조사 방법과 효과 측정이 믿을 만한지",
      },
      {
        id: "p-decision",
        kind: "decision_maker",
        name: "교장 선생님",
        description: "학교 예산과 시설 변경을 최종 승인하는 관중이에요.",
        listensFor: "무엇을 승인해 달라는지, 그만한 효과가 있는지",
      },
    ],
    personaFeedback: [
      {
        personaId: "p-beginner",
        understanding: "followed",
        receivedKeyMessage: true,
        reaction: "수거함 절반이 섞여 있다는 게 충격이었어요. PET, PP가 뭔지는 몰랐지만, 헹궈서 버리면 된다는 건 확실히 알았어요.",
        whatLanded: ["헹궈서 버려야 한다는 사실", "그림 안내판이라는 쉬운 방법"],
        whereLost: ["PET, PP, PS 재질 구분"],
        difficultSectionIds: ["seg-03"],
      },
      {
        personaId: "p-expert",
        understanding: "partly_lost",
        receivedKeyMessage: true,
        reaction: "조사는 탄탄했어요. 그런데 시범 운영 결과를 ‘눈에 띄게’라고만 해서, 얼마나 줄었는지와 비교한 반이 있었는지가 궁금했어요.",
        whatLanded: ["재질별로 나눈 오염률 조사", "212명 설문으로 원인을 찾은 과정"],
        whereLost: ["시범 운영 효과의 크기와 비교 기준"],
        difficultSectionIds: ["seg-07"],
      },
      {
        personaId: "p-decision",
        understanding: "lost",
        receivedKeyMessage: false,
        reaction: "문제는 잘 알겠어요. 그런데 세 가지 방안 중 무엇을 먼저 승인해 달라는 건지, 80만 원이 그만한 효과가 있는지는 끝까지 판단할 수 없었어요.",
        whatLanded: ["오염률 47%라는 문제의 크기"],
        whereLost: ["세 가지 방안 사이의 우선순위", "80만 원 요청과 기대 효과의 연결", "마무리에서 요청하는 결정"],
        difficultSectionIds: ["seg-06", "seg-07"],
      },
    ],
    difficultSections: [
      {
        id: "seg-03",
        startSec: 50,
        endSec: 80,
        transcript: "조사 결과 오염률은 평균 47%였고, 특히 PET와 PP, PS가 섞이는 경우가 가장 많았습니다.",
        highlight: "PET와 PP, PS가 섞이는",
        category: "terminology",
        severity: "low",
        reactions: [{ personaId: "p-beginner", reaction: "PET, PP, PS가 다 플라스틱 아닌가요? 뭐가 다른지 몰랐어요." }],
        reason: "재질 약어를 풀지 않아서, 왜 섞이면 안 되는지 신입생이 스스로 연결하기 어려워요.",
        cause: "TERM_CONFUSION",
        likelihood: "possible",
        pattern: "환경 선생님과 교장 선생님은 47%라는 숫자만으로 충분했지만, 신입생은 약어에서 잠깐 멈췄을 가능성이 있어요. 핵심 흐름을 막지는 않았어요.",
        improvement: {
          suggestion: "약어 대신 실제 물건 이름으로 말하세요.",
          rewrite: "“특히 생수병, 요구르트 병, 컵라면 용기가 한 칸에 섞이는 경우가 가장 많았어요. 셋 다 플라스틱이지만 녹는 온도가 달라 함께 재활용할 수 없어요.”",
        },
      },
      {
        id: "seg-06",
        startSec: 140,
        endSec: 172,
        transcript:
          "그래서 저희는 수거함 위에 그림 안내판을 붙이고, 급식실 옆에 헹굼대를 설치하고, 학급별 분리배출 도우미를 운영하는 방안을 생각했습니다. 헹굼대 설치에는 약 80만 원이 듭니다.",
        highlight: "헹굼대 설치에는 약 80만 원이 듭니다",
        category: "structure",
        severity: "medium",
        reactions: [
          { personaId: "p-decision", reaction: "세 가지 중 무엇을 먼저 하자는 건지 모르겠어요. 80만 원이 지나가듯 나왔어요." },
          { personaId: "p-expert", reaction: "방안들이 어떤 원인에 대응하는지 연결됐으면 좋겠어요." },
        ],
        reason: "방안 세 개를 같은 무게로 나열하고, 유일하게 예산이 드는 요청을 부연처럼 덧붙여 결정할 사람이 우선순위를 알 수 없어요.",
        cause: "PURPOSE_CONFUSION",
        likelihood: "likely",
        pattern: "신입생에게는 셋 다 좋은 아이디어로 들렸지만, 결정권자인 교장 선생님에게는 무엇을 승인해 달라는지가 빠진 목록으로 들렸을 가능성이 높아요.",
        improvement: {
          suggestion: "돈이 들지 않는 방안과 승인이 필요한 방안을 나누고, 승인이 필요한 하나를 분명히 말하세요.",
          rewrite: "“안내판과 도우미는 저희가 바로 시작할 수 있어요. 교장 선생님께 부탁드릴 건 하나, 80만 원으로 급식실 옆 헹굼대를 설치하는 것입니다.”",
        },
      },
      {
        id: "seg-07",
        startSec: 172,
        endSec: 200,
        transcript: "실제로 3학년 2반에서 2주 동안 그림 안내판만 먼저 붙여 봤더니 오염률이 눈에 띄게 줄었습니다.",
        highlight: "오염률이 눈에 띄게 줄었습니다",
        category: "missing_context",
        severity: "high",
        reactions: [
          { personaId: "p-expert", reaction: "얼마나 줄었는지, 붙이지 않은 반과 비교했는지 궁금해요." },
          { personaId: "p-decision", reaction: "효과가 숫자로 없으니 예산을 쓸 근거로 삼기 어려워요." },
          { personaId: "p-beginner", reaction: "안내판이 효과 있었다니 저희 반도 해 보고 싶어요." },
        ],
        reason: "앞에서 47%라는 숫자로 문제를 보여 줬는데, 효과는 숫자 없이 ‘눈에 띄게’로만 말해 해결 방안의 근거가 가장 약한 곳이 됐어요.",
        cause: "LOGIC_GAP",
        likelihood: "high",
        pattern: "신입생은 효과가 있었다는 말로 충분했지만, 환경 선생님은 측정 방법을, 교장 선생님은 예산 대비 효과를 찾으면서 같은 문장에서 반응이 크게 갈렸어요.",
        improvement: {
          suggestion: "시범 운영 전후 오염률을 숫자로 말하고, 비교한 반이 있다면 함께 말하세요.",
          rewrite:
            "“그림 안내판만 붙인 3학년 2반은 2주 만에 오염률이 47%에서 ○○%로 줄었습니다. 헹굼대까지 있으면 더 줄일 수 있어서, 80만 원으로 급식실 옆 헹굼대 설치를 제안드립니다.”",
        },
      },
    ],
    missingExplanations: [
      {
        id: "me-materials",
        term: "PET·PP·PS",
        why: "신입생이 재질이 섞이면 왜 문제인지 연결하지 못했어요.",
        suggestedExplanation: "모두 플라스틱이지만 성분과 녹는 온도가 달라서, 섞이면 함께 재활용할 수 없어요. 생수병은 PET, 요구르트 병은 PP, 컵라면 용기는 PS예요.",
        personaIds: ["p-beginner"],
        sectionId: "seg-03",
      },
      {
        id: "me-contamination",
        term: "오염률 측정 방법",
        why: "환경 선생님이 47%와 시범 운영 결과를 같은 기준으로 비교할 수 있는지 확인하지 못했어요.",
        suggestedExplanation: "수거함 속 전체 개수 중 음식물이 묻었거나 다른 재질이 섞인 개수의 비율이라고 한 줄로 말해 주세요.",
        personaIds: ["p-expert", "p-decision"],
        sectionId: "seg-07",
      },
    ],
    exampleSuggestions: [
      {
        id: "ex-sorting",
        concept: "섞인 플라스틱이 소각되는 과정",
        example: "“선별장에서는 컵라면 용기 하나가 생수병 더미에 섞이면 그 묶음 전체를 재활용하지 못하고 태우기도 해요.”",
        personaIds: ["p-beginner", "p-decision"],
        sectionId: "seg-04",
      },
      {
        id: "ex-cost",
        concept: "80만 원의 기대 효과",
        example: "“헹굼대 하나로 매일 점심 이후 나오는 요구르트 병 약 400개를 헹궈 버릴 수 있어요. 한 해로 치면 8만 개가 넘어요.”",
        personaIds: ["p-decision"],
        sectionId: "seg-06",
      },
    ],
    transcript: transcriptOf([
      { id: "seg-01", startSec: 0, endSec: 22, text: "우리 학교 복도 분리수거함, 한 번쯤 보셨죠? 저희 모둠은 지난 한 달 동안 이 수거함을 매일 열어 봤습니다." },
      { id: "seg-02", startSec: 22, endSec: 50, text: "플라스틱 칸에 들어 있던 쓰레기 중 절반 가까이가 음식물이 묻었거나 다른 재질이 섞여 있었습니다." },
      { id: "seg-03", startSec: 50, endSec: 80, text: "조사 결과 오염률은 평균 47%였고, 특히 PET와 PP, PS가 섞이는 경우가 가장 많았습니다." },
      { id: "seg-04", startSec: 80, endSec: 110, text: "이렇게 섞이면 선별장에서 재활용되지 못하고 결국 소각되거나 매립됩니다." },
      { id: "seg-05", startSec: 110, endSec: 140, text: "원인을 알아보려고 전교생 212명에게 설문을 했는데, 헹궈서 버려야 하는지 몰랐다는 답이 62%였습니다." },
      {
        id: "seg-06",
        startSec: 140,
        endSec: 172,
        text: "그래서 저희는 수거함 위에 그림 안내판을 붙이고, 급식실 옆에 헹굼대를 설치하고, 학급별 분리배출 도우미를 운영하는 방안을 생각했습니다. 헹굼대 설치에는 약 80만 원이 듭니다.",
      },
      { id: "seg-07", startSec: 172, endSec: 200, text: "실제로 3학년 2반에서 2주 동안 그림 안내판만 먼저 붙여 봤더니 오염률이 눈에 띄게 줄었습니다." },
      { id: "seg-08", startSec: 200, endSec: 228, text: "작은 습관이 모이면 학교 전체가 바뀔 수 있습니다. 함께해 주세요. 감사합니다." },
    ]),
    presentationMap: {
      sections: [
        {
          id: "map-observe",
          title: "관찰로 시작",
          startSec: 0,
          endSec: 50,
          summary: "한 달 동안 매일 열어 본 수거함 이야기로 문제를 꺼내요.",
          segmentIds: ["seg-01", "seg-02"],
          difficultSectionIds: [],
        },
        {
          id: "map-data",
          title: "조사 결과",
          startSec: 50,
          endSec: 140,
          summary: "오염률과 설문 결과로 문제의 크기와 원인을 보여 줘요.",
          segmentIds: ["seg-03", "seg-04", "seg-05"],
          difficultSectionIds: ["seg-03"],
        },
        {
          id: "map-plan",
          title: "해결 방안",
          startSec: 140,
          endSec: 200,
          summary: "세 가지 방안과 시범 운영 경험을 소개해요.",
          segmentIds: ["seg-06", "seg-07"],
          difficultSectionIds: ["seg-06", "seg-07"],
        },
        {
          id: "map-close",
          title: "마무리",
          startSec: 200,
          endSec: 228,
          summary: "작은 습관의 힘을 말하며 참여를 부탁해요.",
          segmentIds: ["seg-08"],
          difficultSectionIds: [],
        },
      ],
    },
    audienceHeatmap: {
      cells: [
        { sectionId: "map-observe", personaId: "p-beginner", reception: "clear", evidence: "매일 쓰는 수거함 얘기라 바로 궁금해졌어요." },
        { sectionId: "map-observe", personaId: "p-expert", reception: "clear", evidence: "한 달 동안 직접 관찰했다는 점에서 신뢰가 갔어요." },
        { sectionId: "map-observe", personaId: "p-decision", reception: "clear", evidence: "학교 시설 얘기라 제 일로 들렸어요." },
        { sectionId: "map-data", personaId: "p-beginner", reception: "partial", evidence: "PET, PP, PS가 다 플라스틱 아닌가요? 뭐가 다른지 몰랐어요." },
        { sectionId: "map-data", personaId: "p-expert", reception: "clear", evidence: "재질별로 나눠 본 조사와 212명 설문이 탄탄했어요." },
        { sectionId: "map-data", personaId: "p-decision", reception: "clear", evidence: "47%라는 숫자로 문제의 크기가 보였어요." },
        { sectionId: "map-plan", personaId: "p-beginner", reception: "clear", evidence: "안내판이 효과 있었다니 저희 반도 해 보고 싶어요." },
        { sectionId: "map-plan", personaId: "p-expert", reception: "partial", evidence: "얼마나 줄었는지, 붙이지 않은 반과 비교했는지 궁금해요." },
        { sectionId: "map-plan", personaId: "p-decision", reception: "lost", evidence: "세 가지 중 무엇을 승인해 달라는 건지, 80만 원이 그만한 효과가 있는지 모르겠어요." },
        { sectionId: "map-close", personaId: "p-beginner", reception: "clear", evidence: "함께하자는 말에 저도 참여하고 싶어졌어요." },
        { sectionId: "map-close", personaId: "p-expert", reception: "clear", evidence: "습관 변화라는 결론은 조사 결과와 잘 이어져요." },
        { sectionId: "map-close", personaId: "p-decision", reception: "partial", evidence: "함께해 달라는 말은 좋은데, 제게 요청하는 결정은 끝까지 없었어요." },
      ],
    },
    discovery: {
      headline: "같은 ‘눈에 띄게 줄었습니다’를 두고 신입생은 바로 해 보고 싶어졌지만, 결정해야 할 교장 선생님은 예산을 쓸 근거를 찾지 못했어요.",
      detail: "시범 운영 결과를 전후 숫자로 말하고 80만 원 요청과 한 문장으로 이으면, 세 관중이 같은 결론에 도착할 수 있어요.",
      sectionId: "map-plan",
      difficultSectionId: "seg-07",
      personaIds: ["p-beginner", "p-decision"],
    },
    keyMoments: [
      {
        id: "moment-1",
        kind: "interest_peak",
        startSec: 22,
        title: "관심이 가장 크게 올라간 구간",
        detail: "플라스틱 칸의 절반 가까이가 섞여 있었다는 말에 세 관중 모두 문제를 자기 일처럼 느꼈을 가능성이 높아요.",
        sectionId: "map-observe",
        personaIds: ["p-beginner", "p-expert", "p-decision"],
      },
      {
        id: "moment-2",
        kind: "first_drop",
        startSec: 140,
        title: "이해가 처음으로 떨어진 구간",
        detail: "방안 세 개와 80만 원이 한꺼번에 나오면서 교장 선생님이 무엇을 결정해야 하는지 처음 놓쳤을 가능성이 높아요.",
        sectionId: "map-plan",
        difficultSectionId: "seg-06",
        personaIds: ["p-decision"],
      },
      {
        id: "moment-3",
        kind: "common_question",
        startSec: 172,
        title: "여러 관중이 공통으로 질문을 가진 구간",
        detail: "‘눈에 띄게 줄었다’는 말에 환경 선생님과 교장 선생님 모두 ‘얼마나?’라고 물었을 가능성이 있어요.",
        sectionId: "map-plan",
        difficultSectionId: "seg-07",
        personaIds: ["p-expert", "p-decision"],
      },
    ],
    naturalQuestions: [
      { id: "question-1", question: "시범 운영 2주 동안 오염률은 정확히 몇 %까지 줄었나요?", personaIds: ["p-expert", "p-decision"], sectionId: "map-plan", startSec: 172 },
      { id: "question-2", question: "세 가지 방안 중 무엇을 가장 먼저 해야 하나요?", personaIds: ["p-decision"], sectionId: "map-plan", startSec: 140 },
      { id: "question-3", question: "PET, PP, PS는 어떻게 구별하나요?", personaIds: ["p-beginner"], sectionId: "map-data", startSec: 50 },
    ],
  },
};
